apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: configuration-azure-assume-gcp
  annotations:
    meta.crossplane.io/maintainer: Upbound <support@upbound.io>
    meta.crossplane.io/source: github.com/upbound/configuration-azure-assume-gcp
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      This Crossplane configuration demonstrates how to create Azure AKS clusters and assume a role in AWS using the AssumeRoleWithWebIdentity method.
    meta.crossplane.io/readme: |
      This Crossplane configuration demonstrates how to create Azure AKS clusters and assume a role in AWS using the AssumeRoleWithWebIdentity method.

spec:
  crossplane:
    version: ">=v1.14.1-0"
  dependsOn:
    - provider: xpkg.upbound.io/upbound/provider-azure-containerservice
      # renovate: datasource=github-releases depName=upbound/provider-azure
      version: "v0.42.1"
    - configuration: xpkg.upbound.io/upbound/configuration-azure-network
      # renovate: datasource=github-releases depName=upbound/configuration-azure-network
      version: "v0.8.0"
    - provider: xpkg.upbound.io/crossplane-contrib/provider-helm
      # renovate: datasource=github-releases depName=crossplane-contrib/provider-helm
      version: "v0.17.0"
    - provider: xpkg.upbound.io/crossplane-contrib/provider-kubernetes
      # renovate: datasource=github-releases depName=crossplane-contrib/provider-kubernetes
      version: "v0.12.1"
    - provider: xpkg.upbound.io/upbound/provider-azure-managedidentity
      # renovate: datasource=github-releases depName=crossplane-contrib/provider-upjet-azure
      version: "v0.42.1"
    - function: xpkg.upbound.io/crossplane-contrib/function-sequencer
      # renovate: datasource=github-releases depName=crossplane-contrib/function-sequencer
      version: "v0.1.2"
